/*
 * generated by Xtext 2.25.0
 */
package org.prettyprinter.sml.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.prettyprinter.sml.ui.internal.SmlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SMLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(SmlActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		SmlActivator activator = SmlActivator.getInstance();
		return activator != null ? activator.getInjector(SmlActivator.ORG_PRETTYPRINTER_SML_SML) : null;
	}

}
