/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.myspectra.ide;


/**
 * Use this class to register ide components.
 */
public class MySpectraIdeModule extends AbstractMySpectraIdeModule {
}
