<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="qvtoperational" nsURI="http://www.schema.omg.org/spec/QVT/1.0/qvtoperational"
    nsPrefix="qvtoperational">
  <eClassifiers xsi:type="ecore:EClass" name="MappingBody" eSuperTypes="#//OperationBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="initSection" upperBound="-1"
        eType="#//ExpressionGO" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endSection" upperBound="-1"
        eType="#//ExpressionGO" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="population_section" eType="#//PopulationSection"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Helper" eSuperTypes="#//ImperativeOperation #//Module">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isQuery" eType="ecore:EDataType emof.ecore#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="helper_header" lowerBound="1"
        eType="#//HelperHeader" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//ExpressionGO"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression_block" eType="#//ExpressionBlock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResolveExp" eSuperTypes="#//ExpressionGO">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="one" eType="ecore:EDataType emof.ecore#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isInverse" eType="ecore:EDataType emof.ecore#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDeferred" eType="ecore:EDataType emof.ecore#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//ExpressionGO"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//ExpressionGO"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResolveInExp" eSuperTypes="#//ResolveExp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inMapping" eType="#//MappingOperation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationalTransformation" eSuperTypes="#//Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="intermediateClass" upperBound="-1"
        eType="ecore:EClass emof.ecore#//Class"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refined" eType="#//ExpressionGO"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intermediateProperty" upperBound="-1"
        eType="ecore:EClass emof.ecore#//Property"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelParameter" upperBound="-1"
        eType="#//ModelParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relation" upperBound="-1"
        eType="#//ExpressionGO" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transformation_h" lowerBound="1"
        eType="#//TransformationHeader" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="module_element" upperBound="-1"
        eType="#//ImperativeOperation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MappingParameter" eSuperTypes="#//VarParameter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="refinedDomain" eType="#//ExpressionGO"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extent" eType="#//ModelParameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MappingOperation" eSuperTypes="#//ImperativeOperation #//Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="disjunct" upperBound="-1"
        eType="#//MappingOperation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refinedRelation" eType="#//ExpressionGO"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="merged" upperBound="-1"
        eType="#//MappingOperation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inherited" upperBound="-1"
        eType="#//MappingOperation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="when" upperBound="-1" eType="#//ExpressionGO"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="where" upperBound="-1"
        eType="#//ExpressionGO" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapping_full_header" lowerBound="1"
        eType="#//MappingFullHeader" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapping_body" eType="#//MappingBody"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MappingCallExp" eSuperTypes="#//ImperativeCallExp">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isStrict" eType="ecore:EDataType emof.ecore#//Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constructor" eSuperTypes="#//ImperativeOperation #//Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constructor_header" lowerBound="1"
        eType="#//ConstructorHeader" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression_block" eType="#//ExpressionBlock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContextualProperty" eSuperTypes="#//ImperativeOperation #//Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="initExpression" eType="#//ExpressionGO"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="property_key" lowerBound="1"
        upperBound="-1" eType="#//PropertyKey"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declarator" lowerBound="1"
        eType="#//Declarator" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntryOperation" eSuperTypes="#//ImperativeOperation #//Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entry_header" lowerBound="1"
        eType="#//EntryHeader" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression_block" eType="#//ExpressionBlock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImperativeCallExp" eSuperTypes="#//ExpressionGO">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isVirtual" eType="ecore:EDataType emof.ecore#//Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImperativeOperation" eSuperTypes="emof.ecore#//Operation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" eType="#//VarParameter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="result" upperBound="-1"
        eType="#//VarParameter" containment="true" eOpposite="#//VarParameter/resOwner"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="overridden" eType="#//ImperativeOperation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//OperationBody"
        containment="true" eOpposite="#//OperationBody/operation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DirectionKind">
    <eLiterals name="in"/>
    <eLiterals name="inout" value="1"/>
    <eLiterals name="out" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Library" eSuperTypes="#//Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="library_h" lowerBound="1"
        eType="#//LibraryHeader" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="module_element" upperBound="-1"
        eType="#//ImperativeOperation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelParameter" eSuperTypes="#//VarParameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModelType" eSuperTypes="emof.ecore#//URIExtent #//Module emof.ecore#//Class">
    <eStructuralFeatures xsi:type="ecore:EReference" name="metamodel" upperBound="-1"
        eType="ecore:EClass emof.ecore#//Package"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additionalCondition" upperBound="-1"
        eType="#//ExpressionGO" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conformanceKind" eType="ecore:EDataType emof.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="compliance_kind" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="packageref_list" upperBound="-1"
        eType="#//PackageRefGO" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modeltype_where" eType="#//ExpressionBlock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Module" eSuperTypes="emof.ecore#//Package">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedTag" upperBound="-1"
        eType="ecore:EClass emof.ecore#//Tag" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entry" eType="ecore:EClass emof.ecore#//Operation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configProperty" upperBound="-1"
        eType="ecore:EClass emof.ecore#//Property"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="moduleImport" upperBound="-1"
        eType="#//ModuleImport" containment="true" eOpposite="#//ModuleImport/module"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usedModelType" upperBound="-1"
        eType="#//ModelType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isBlackbox" eType="ecore:EDataType emof.ecore#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedVariable" upperBound="-1"
        eType="#//ExpressionGO" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleImport" eSuperTypes="emof.ecore#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="binding" upperBound="-1"
        eType="#//ModelType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" eType="#//Module"
        transient="true" eOpposite="#//Module/moduleImport"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="importedModule" lowerBound="1"
        eType="#//Module"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//ImportKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unit" eType="#//UnitRefGO"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ImportKind">
    <eLiterals name="extension"/>
    <eLiterals name="access" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VarParameter" eSuperTypes="emof.ecore#//Parameter #//ExpressionGO">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ctxOwner" eType="#//ImperativeOperation"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resOwner" eType="#//ImperativeOperation"
        transient="true" eOpposite="#//ImperativeOperation/result"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//DirectionKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declarator" lowerBound="1"
        eType="#//Declarator" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationBody" eSuperTypes="emof.ecore#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" eType="#//ImperativeOperation"
        transient="true" eOpposite="#//ImperativeOperation/body"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" upperBound="-1"
        eType="#//ExpressionGO" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" upperBound="-1"
        eType="#//ExpressionGO" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstructorBody" eSuperTypes="#//OperationBody"/>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectExp" eSuperTypes="#//ExpressionGO">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referredObject" lowerBound="1"
        eType="#//ExpressionGO"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="#//ConstructorBody"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TopLevelGO">
    <eStructuralFeatures xsi:type="ecore:EReference" name="unit_element" upperBound="-1"
        eType="#//Module" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="moduleimport" upperBound="-1"
        eType="#//ModuleImport" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnitRefGO">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TagGO" eSuperTypes="#//Module #//ImperativeOperation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tagid" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scoped_identifier" lowerBound="1"
        eType="#//ScopedIdentifier" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tagvalue" eType="#//ExpressionGO"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MetaModelGO" eSuperTypes="#//Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="metamodel_h" lowerBound="1"
        eType="#//MetaModelHeader" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metamodel_element" upperBound="-1"
        eType="#//MetaModelElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AccessDecl" eSuperTypes="#//Module #//ImperativeOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="access_usage" lowerBound="1"
        eType="#//AccessUsage" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeDef" eSuperTypes="#//Module #//ImperativeOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typespec" lowerBound="1"
        eType="#//TypeSpec" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typedef_condition" eType="#//ExpressionGO"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransformationHeader">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifier" upperBound="-1"
        eType="#//GeneralQualifier"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transformation_signature"
        lowerBound="1" eType="#//SimpleSignature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transformation_usage_refine"
        eType="#//TransformationUsageRefine" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleSignature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="param_list" eType="#//ParamList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransformationUsageRefine">
    <eStructuralFeatures xsi:type="ecore:EReference" name="module_usage" eType="#//ModuleUsageGO"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transformation_refine"
        eType="#//ModuleRefGO" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleRefGO">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scoped_identifier" lowerBound="1"
        eType="#//ScopedIdentifier" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="simple_signature" eType="#//SimpleSignature"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GeneralQualifier">
    <eLiterals name="blackbox"/>
    <eLiterals name="abstract" value="1"/>
    <eLiterals name="static" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleUsageGO">
    <eStructuralFeatures xsi:type="ecore:EReference" name="access_usage" eType="#//AccessUsage"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extends_usage" eType="#//ExtendsUsage"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LibraryHeader">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="library_signature" eType="#//SimpleSignature"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="module_usage" eType="#//ModuleUsageGO"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AccessUsage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="module_kind" eType="#//ModuleKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="moduleref_list" upperBound="-1"
        eType="#//ModuleRefGO" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtendsUsage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="module_kind" eType="#//ModuleKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="moduleref_list" upperBound="-1"
        eType="#//ModuleRefGO" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ModuleKind">
    <eLiterals name="transformation"/>
    <eLiterals name="library" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScopedIdentifier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParamList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="param" upperBound="-1"
        eType="#//VarParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassifierGO" eSuperTypes="#//ImperativeOperation #//Module">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifier_h" lowerBound="1"
        eType="#//ClassifierHeader" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifier_feature_list"
        eType="#//ClassifierFeatureList" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Declarator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typespec" lowerBound="1"
        eType="#//TypeSpec" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="init_part" eType="#//InitPart"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scoped_identifier" eType="#//ScopedIdentifier"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeSpec">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type_reference" lowerBound="1"
        eType="#//TypeReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extent_location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scoped_identifier" eType="#//ScopedIdentifier"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="complex_type" eType="#//ComplexType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComplexType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="complex_type_key" eType="#//ComplexTypeKey"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="collection_key" eType="#//CollectionKey"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typespec" upperBound="2"
        eType="#//TypeSpec" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declarator_list" eType="#//DeclaratorList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ComplexTypeKey">
    <eLiterals name="Collection"/>
    <eLiterals name="Set" value="1"/>
    <eLiterals name="OrderedSet" value="2"/>
    <eLiterals name="Sequence" value="3"/>
    <eLiterals name="Bag" value="4"/>
    <eLiterals name="List" value="5"/>
    <eLiterals name="Dict" value="6"/>
    <eLiterals name="Tuple" value="7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeclaratorList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="declarator" upperBound="-1"
        eType="#//Declarator" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InitPart">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="init_op" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//ExpressionGO" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionSemiList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" upperBound="-1"
        eType="#//ExpressionGO" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression_semi_list" lowerBound="1"
        eType="#//ExpressionSemiList" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionBlock">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression_list" eType="#//ExpressionList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PackageRefGO">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scoped_identifier" eType="#//ScopedIdentifier"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MetaModelHeader">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scoped_identifier" lowerBound="1"
        eType="#//ScopedIdentifier" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MetaModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifier" eType="#//ClassifierGO"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumeration" eType="#//EnumerationGO"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tag" eType="#//TagGO" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumerationGO">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumeration_h" eType="#//EnumerationHeader"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassifierHeader">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifier_info" lowerBound="1"
        eType="#//ClassifierInfo" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scoped_identifier" lowerBound="1"
        eType="#//ScopedIdentifier" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifier_extension" eType="#//ClassifierExtension"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassifierFeatureList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classifier_feature" upperBound="-1"
        eType="#//ClassifierFeature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassifierInfo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifier" upperBound="-1"
        eType="#//GeneralQualifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassifierExtension">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scoped_identifier_list"
        lowerBound="1" eType="#//ScopedIdentifierList" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScopedIdentifierList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scoped_identifier_list"
        upperBound="-1" eType="#//ScopedIdentifier" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassifierFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature_qualifier" eType="#//FeatureQualifier"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declarator" lowerBound="1"
        eType="#//Declarator" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="multiplicity" eType="#//Multiplicity"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="opposite_property" eType="#//OppositeProperty"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="complete_signature" eType="#//CompleteSignature"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tag" eType="#//TagGO" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Multiplicity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity_range" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OppositeProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="multiplicity" eType="#//Multiplicity"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StereotypeQualifier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureQualifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stereotype_qualifier" eType="#//StereotypeQualifier"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="feature_key" upperBound="-1"
        eType="#//FeatureKey"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FeatureKey">
    <eLiterals name="composes"/>
    <eLiterals name="references" value="1"/>
    <eLiterals name="readonly" value="2"/>
    <eLiterals name="derived" value="3"/>
    <eLiterals name="static" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompleteSignature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="simple_signature" lowerBound="1"
        eType="#//SimpleSignature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="param_list" eType="#//ParamList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumerationHeader">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PropertyKey">
    <eLiterals name="derived"/>
    <eLiterals name="literal" value="1"/>
    <eLiterals name="configuration" value="2"/>
    <eLiterals name="property" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HelperInfo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifier" upperBound="-1"
        eType="#//GeneralQualifier"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="helper_kind" eType="#//HelperKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HelperHeader">
    <eStructuralFeatures xsi:type="ecore:EReference" name="helper_info" lowerBound="1"
        eType="#//HelperInfo" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scope_identifier" lowerBound="1"
        eType="#//ScopedIdentifier" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="complete_signature" lowerBound="1"
        eType="#//CompleteSignature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="HelperKind">
    <eLiterals name="helper"/>
    <eLiterals name="query" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstructorHeader">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifier" upperBound="-1"
        eType="#//GeneralQualifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scoped_identifier" lowerBound="1"
        eType="#//ScopedIdentifier" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="simple_signature" lowerBound="1"
        eType="#//SimpleSignature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntryHeader">
    <eStructuralFeatures xsi:type="ecore:EReference" name="simple_signature" lowerBound="1"
        eType="#//SimpleSignature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MappingHeader">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifier" upperBound="-1"
        eType="#//GeneralQualifier"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="param_direction" eType="#//DirectionKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scoped_identifier" lowerBound="1"
        eType="#//ScopedIdentifier" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="complete_signature" lowerBound="1"
        eType="#//CompleteSignature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapping_extra" upperBound="-1"
        eType="#//MappingExtra" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MappingFullHeader">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapping_header" lowerBound="1"
        eType="#//MappingHeader" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="when" eType="#//ExpressionBlock"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="where" eType="#//ExpressionBlock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MappingExtra">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapping_extension" eType="#//MappingExtension"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapping_refinement" eType="#//MappingRefinement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MappingExtension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mapping_extension_key"
        lowerBound="1" eType="#//MappingExtensionKey"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scoped_identifier_list"
        lowerBound="1" eType="#//ScopedIdentifierList" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MappingRefinement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scoped_identifier" lowerBound="1"
        eType="#//ScopedIdentifier" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MappingExtensionKey">
    <eLiterals name="inherits"/>
    <eLiterals name="merges" value="1"/>
    <eLiterals name="disjuncts" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PopulationSection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression_list" eType="#//ExpressionList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression_block" eType="#//ExpressionBlock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionGO">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dummyContent" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CollectionKey">
    <eLiterals name="Collection"/>
    <eLiterals name="Set" value="1"/>
    <eLiterals name="OrderedSet" value="2"/>
    <eLiterals name="Sequence" value="3"/>
    <eLiterals name="Bag" value="4"/>
    <eLiterals name="List" value="5"/>
  </eClassifiers>
</ecore:EPackage>
