/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.xcore.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.xcore.XcoreRuntimeModule;
import org.xtext.example.xcore.XcoreStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class XcoreIdeSetup extends XcoreStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new XcoreRuntimeModule(), new XcoreIdeModule()));
	}
	
}
