/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.myspectra.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MySpectraUiModule extends AbstractMySpectraUiModule {

	public MySpectraUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
