/*
 * generated by Xtext 2.25.0
 */
package org.eclipse.eatxt.full.optimized.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.eatxt.full.optimized.services.EatxtGrammarAccess;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class EatxtSyntacticSequencer extends AbstractSyntacticSequencer {

	protected EatxtGrammarAccess grammarAccess;
	protected AbstractElementAlias match_AUTOSAREvent___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_5__q;
	protected AbstractElementAlias match_Actor___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q;
	protected AbstractElementAlias match_Actuator___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q;
	protected AbstractElementAlias match_Allocation___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_6__q;
	protected AbstractElementAlias match_AnalysisFunctionType_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q;
	protected AbstractElementAlias match_AnalysisLevel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q;
	protected AbstractElementAlias match_ArchitecturalModel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_6__q;
	protected AbstractElementAlias match_AttributeQuantificationConstraint___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q;
	protected AbstractElementAlias match_BasicSoftwareFunctionType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q;
	protected AbstractElementAlias match_BehaviorConstraintBindingEvent___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q;
	protected AbstractElementAlias match_BehaviorConstraintType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q;
	protected AbstractElementAlias match_Behavior___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q;
	protected AbstractElementAlias match_CommunicationHardwarePin___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q;
	protected AbstractElementAlias match_ComputationConstraint___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q;
	protected AbstractElementAlias match_Dependability___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_20__q;
	protected AbstractElementAlias match_DesignFunctionType_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q;
	protected AbstractElementAlias match_DesignLevel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q;
	protected AbstractElementAlias match_EABoolean___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q;
	protected AbstractElementAlias match_EANumerical___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q;
	protected AbstractElementAlias match_EAPackage___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q;
	protected AbstractElementAlias match_EAString___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q;
	protected AbstractElementAlias match_ElectricalComponent___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q;
	protected AbstractElementAlias match_EnumerationLiteral___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_5__q;
	protected AbstractElementAlias match_Environment___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_9__q;
	protected AbstractElementAlias match_ErrorModelType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_16__q;
	protected AbstractElementAlias match_ExtensionPoint___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_5__q;
	protected AbstractElementAlias match_ExternalEvent___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_5__q;
	protected AbstractElementAlias match_FeatureModel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q;
	protected AbstractElementAlias match_FunctionClientServerInterface___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q;
	protected AbstractElementAlias match_FunctionalDevice___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q;
	protected AbstractElementAlias match_FunctionalSafetyConcept___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q;
	protected AbstractElementAlias match_GenericConstraintSet___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q;
	protected AbstractElementAlias match_Ground___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_9__q;
	protected AbstractElementAlias match_HardwareComponentType_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q;
	protected AbstractElementAlias match_HardwareFunctionType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q;
	protected AbstractElementAlias match_HardwarePort___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_9__q;
	protected AbstractElementAlias match_IOHardwarePin___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q;
	protected AbstractElementAlias match_ImplementationLevel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q;
	protected AbstractElementAlias match_InternalBinding___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_6__q;
	protected AbstractElementAlias match_LocalDeviceManager___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q;
	protected AbstractElementAlias match_LogicalPath___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q;
	protected AbstractElementAlias match_Mission___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_5__q;
	protected AbstractElementAlias match_ModeEvent___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q;
	protected AbstractElementAlias match_Node___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q;
	protected AbstractElementAlias match_Operation___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q;
	protected AbstractElementAlias match_PortGroup___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q;
	protected AbstractElementAlias match_PowerHardwarePin___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q;
	protected AbstractElementAlias match_Requirement_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_9__q;
	protected AbstractElementAlias match_RequirementsHierarchy_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_9__q;
	protected AbstractElementAlias match_RequirementsModel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q;
	protected AbstractElementAlias match_Satisfy___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q;
	protected AbstractElementAlias match_Sensor___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q;
	protected AbstractElementAlias match_Situation___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q;
	protected AbstractElementAlias match_StateEvent___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q;
	protected AbstractElementAlias match_SystemModel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_11__q;
	protected AbstractElementAlias match_TechnicalSafetyConcept___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q;
	protected AbstractElementAlias match_Timing___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_9__q;
	protected AbstractElementAlias match_TransitionEvent_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q;
	protected AbstractElementAlias match_UseCase___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_11__q;
	protected AbstractElementAlias match_VVActualOutcome___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q;
	protected AbstractElementAlias match_VVCase___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q;
	protected AbstractElementAlias match_VVIntendedOutcome___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q;
	protected AbstractElementAlias match_VVProcedure___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q;
	protected AbstractElementAlias match_VVStimuli___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q;
	protected AbstractElementAlias match_VVTarget___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q;
	protected AbstractElementAlias match_Variability___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q;
	protected AbstractElementAlias match_VehicleLevelBinding___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q;
	protected AbstractElementAlias match_VehicleLevel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q;
	protected AbstractElementAlias match_VerificationValidation___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q;
	protected AbstractElementAlias match_Warrant___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (EatxtGrammarAccess) access;
		match_AUTOSAREvent___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_5__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getAUTOSAREventAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getAUTOSAREventAccess().getRightCurlyBracketKeyword_2_5()));
		match_Actor___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getActorAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getActorAccess().getRightCurlyBracketKeyword_2_7()));
		match_Actuator___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getActuatorAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getActuatorAccess().getRightCurlyBracketKeyword_2_12()));
		match_Allocation___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_6__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getAllocationAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getAllocationAccess().getRightCurlyBracketKeyword_2_6()));
		match_AnalysisFunctionType_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getAnalysisFunctionType_ImplAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getAnalysisFunctionType_ImplAccess().getRightCurlyBracketKeyword_2_12()));
		match_AnalysisLevel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getAnalysisLevelAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getAnalysisLevelAccess().getRightCurlyBracketKeyword_2_8()));
		match_ArchitecturalModel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_6__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getArchitecturalModelAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getArchitecturalModelAccess().getRightCurlyBracketKeyword_2_6()));
		match_AttributeQuantificationConstraint___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getAttributeQuantificationConstraintAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getAttributeQuantificationConstraintAccess().getRightCurlyBracketKeyword_2_7()));
		match_BasicSoftwareFunctionType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getBasicSoftwareFunctionTypeAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getBasicSoftwareFunctionTypeAccess().getRightCurlyBracketKeyword_2_12()));
		match_BehaviorConstraintBindingEvent___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getBehaviorConstraintBindingEventAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getBehaviorConstraintBindingEventAccess().getRightCurlyBracketKeyword_2_13()));
		match_BehaviorConstraintType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getBehaviorConstraintTypeAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getBehaviorConstraintTypeAccess().getRightCurlyBracketKeyword_2_13()));
		match_Behavior___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getBehaviorAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getBehaviorAccess().getRightCurlyBracketKeyword_2_10()));
		match_CommunicationHardwarePin___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getCommunicationHardwarePinAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getCommunicationHardwarePinAccess().getRightCurlyBracketKeyword_2_7()));
		match_ComputationConstraint___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getComputationConstraintAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getComputationConstraintAccess().getRightCurlyBracketKeyword_2_7()));
		match_Dependability___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_20__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getDependabilityAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getDependabilityAccess().getRightCurlyBracketKeyword_2_20()));
		match_DesignFunctionType_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getDesignFunctionType_ImplAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getDesignFunctionType_ImplAccess().getRightCurlyBracketKeyword_2_12()));
		match_DesignLevel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getDesignLevelAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getDesignLevelAccess().getRightCurlyBracketKeyword_2_10()));
		match_EABoolean___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getEABooleanAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getEABooleanAccess().getRightCurlyBracketKeyword_2_7()));
		match_EANumerical___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getEANumericalAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getEANumericalAccess().getRightCurlyBracketKeyword_2_10()));
		match_EAPackage___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getEAPackageAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getEAPackageAccess().getRightCurlyBracketKeyword_2_7()));
		match_EAString___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getEAStringAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getEAStringAccess().getRightCurlyBracketKeyword_2_7()));
		match_ElectricalComponent___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getElectricalComponentAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getElectricalComponentAccess().getRightCurlyBracketKeyword_2_13()));
		match_EnumerationLiteral___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_5__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getEnumerationLiteralAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getEnumerationLiteralAccess().getRightCurlyBracketKeyword_2_5()));
		match_Environment___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_9__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getEnvironmentAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getEnvironmentAccess().getRightCurlyBracketKeyword_2_9()));
		match_ErrorModelType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_16__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getErrorModelTypeAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getErrorModelTypeAccess().getRightCurlyBracketKeyword_2_16()));
		match_ExtensionPoint___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_5__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getExtensionPointAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getExtensionPointAccess().getRightCurlyBracketKeyword_2_5()));
		match_ExternalEvent___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_5__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getExternalEventAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getExternalEventAccess().getRightCurlyBracketKeyword_2_5()));
		match_FeatureModel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getFeatureModelAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getFeatureModelAccess().getRightCurlyBracketKeyword_2_10()));
		match_FunctionClientServerInterface___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getFunctionClientServerInterfaceAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getFunctionClientServerInterfaceAccess().getRightCurlyBracketKeyword_2_8()));
		match_FunctionalDevice___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getFunctionalDeviceAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getFunctionalDeviceAccess().getRightCurlyBracketKeyword_2_12()));
		match_FunctionalSafetyConcept___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getFunctionalSafetyConceptAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getFunctionalSafetyConceptAccess().getRightCurlyBracketKeyword_2_10()));
		match_GenericConstraintSet___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getGenericConstraintSetAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getGenericConstraintSetAccess().getRightCurlyBracketKeyword_2_8()));
		match_Ground___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_9__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getGroundAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getGroundAccess().getRightCurlyBracketKeyword_2_9()));
		match_HardwareComponentType_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getHardwareComponentType_ImplAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getHardwareComponentType_ImplAccess().getRightCurlyBracketKeyword_2_12()));
		match_HardwareFunctionType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getHardwareFunctionTypeAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getHardwareFunctionTypeAccess().getRightCurlyBracketKeyword_2_13()));
		match_HardwarePort___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_9__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getHardwarePortAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getHardwarePortAccess().getRightCurlyBracketKeyword_2_9()));
		match_IOHardwarePin___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getIOHardwarePinAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getIOHardwarePinAccess().getRightCurlyBracketKeyword_2_8()));
		match_ImplementationLevel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getImplementationLevelAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getImplementationLevelAccess().getRightCurlyBracketKeyword_2_7()));
		match_InternalBinding___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_6__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getInternalBindingAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getInternalBindingAccess().getRightCurlyBracketKeyword_2_6()));
		match_LocalDeviceManager___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getLocalDeviceManagerAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getLocalDeviceManagerAccess().getRightCurlyBracketKeyword_2_12()));
		match_LogicalPath___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getLogicalPathAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getLogicalPathAccess().getRightCurlyBracketKeyword_2_13()));
		match_Mission___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_5__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getMissionAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getMissionAccess().getRightCurlyBracketKeyword_2_5()));
		match_ModeEvent___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getModeEventAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getModeEventAccess().getRightCurlyBracketKeyword_2_7()));
		match_Node___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getNodeAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getNodeAccess().getRightCurlyBracketKeyword_2_13()));
		match_Operation___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getOperationAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getOperationAccess().getRightCurlyBracketKeyword_2_7()));
		match_PortGroup___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getPortGroupAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getPortGroupAccess().getRightCurlyBracketKeyword_2_7()));
		match_PowerHardwarePin___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getPowerHardwarePinAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getPowerHardwarePinAccess().getRightCurlyBracketKeyword_2_7()));
		match_Requirement_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_9__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getRequirement_ImplAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getRequirement_ImplAccess().getRightCurlyBracketKeyword_2_9()));
		match_RequirementsHierarchy_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_9__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getRequirementsHierarchy_ImplAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getRequirementsHierarchy_ImplAccess().getRightCurlyBracketKeyword_2_9()));
		match_RequirementsModel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getRequirementsModelAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getRequirementsModelAccess().getRightCurlyBracketKeyword_2_13()));
		match_Satisfy___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getSatisfyAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getSatisfyAccess().getRightCurlyBracketKeyword_2_8()));
		match_Sensor___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getSensorAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getSensorAccess().getRightCurlyBracketKeyword_2_12()));
		match_Situation___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getSituationAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getSituationAccess().getRightCurlyBracketKeyword_2_7()));
		match_StateEvent___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getStateEventAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getStateEventAccess().getRightCurlyBracketKeyword_2_7()));
		match_SystemModel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_11__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getSystemModelAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getSystemModelAccess().getRightCurlyBracketKeyword_2_11()));
		match_TechnicalSafetyConcept___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getTechnicalSafetyConceptAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getTechnicalSafetyConceptAccess().getRightCurlyBracketKeyword_2_10()));
		match_Timing___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_9__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getTimingAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getTimingAccess().getRightCurlyBracketKeyword_2_9()));
		match_TransitionEvent_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getTransitionEvent_ImplAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getTransitionEvent_ImplAccess().getRightCurlyBracketKeyword_2_10()));
		match_UseCase___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_11__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getUseCaseAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getUseCaseAccess().getRightCurlyBracketKeyword_2_11()));
		match_VVActualOutcome___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getVVActualOutcomeAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getVVActualOutcomeAccess().getRightCurlyBracketKeyword_2_8()));
		match_VVCase___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getVVCaseAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getVVCaseAccess().getRightCurlyBracketKeyword_2_12()));
		match_VVIntendedOutcome___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getVVIntendedOutcomeAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getVVIntendedOutcomeAccess().getRightCurlyBracketKeyword_2_7()));
		match_VVProcedure___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getVVProcedureAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getVVProcedureAccess().getRightCurlyBracketKeyword_2_10()));
		match_VVStimuli___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getVVStimuliAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getVVStimuliAccess().getRightCurlyBracketKeyword_2_7()));
		match_VVTarget___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getVVTargetAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getVVTargetAccess().getRightCurlyBracketKeyword_2_8()));
		match_Variability___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getVariabilityAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getVariabilityAccess().getRightCurlyBracketKeyword_2_13()));
		match_VehicleLevelBinding___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getVehicleLevelBindingAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getVehicleLevelBindingAccess().getRightCurlyBracketKeyword_2_8()));
		match_VehicleLevel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getVehicleLevelAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getVehicleLevelAccess().getRightCurlyBracketKeyword_2_8()));
		match_VerificationValidation___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getVerificationValidationAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getVerificationValidationAccess().getRightCurlyBracketKeyword_2_10()));
		match_Warrant___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getWarrantAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getWarrantAccess().getRightCurlyBracketKeyword_2_10()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_AUTOSAREvent___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_5__q.equals(syntax))
				emit_AUTOSAREvent___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_5__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Actor___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q.equals(syntax))
				emit_Actor___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Actuator___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q.equals(syntax))
				emit_Actuator___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Allocation___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_6__q.equals(syntax))
				emit_Allocation___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_6__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_AnalysisFunctionType_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q.equals(syntax))
				emit_AnalysisFunctionType_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_AnalysisLevel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q.equals(syntax))
				emit_AnalysisLevel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_ArchitecturalModel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_6__q.equals(syntax))
				emit_ArchitecturalModel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_6__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_AttributeQuantificationConstraint___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q.equals(syntax))
				emit_AttributeQuantificationConstraint___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_BasicSoftwareFunctionType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q.equals(syntax))
				emit_BasicSoftwareFunctionType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_BehaviorConstraintBindingEvent___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q.equals(syntax))
				emit_BehaviorConstraintBindingEvent___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_BehaviorConstraintType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q.equals(syntax))
				emit_BehaviorConstraintType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Behavior___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q.equals(syntax))
				emit_Behavior___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_CommunicationHardwarePin___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q.equals(syntax))
				emit_CommunicationHardwarePin___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_ComputationConstraint___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q.equals(syntax))
				emit_ComputationConstraint___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Dependability___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_20__q.equals(syntax))
				emit_Dependability___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_20__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_DesignFunctionType_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q.equals(syntax))
				emit_DesignFunctionType_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_DesignLevel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q.equals(syntax))
				emit_DesignLevel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_EABoolean___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q.equals(syntax))
				emit_EABoolean___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_EANumerical___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q.equals(syntax))
				emit_EANumerical___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_EAPackage___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q.equals(syntax))
				emit_EAPackage___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_EAString___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q.equals(syntax))
				emit_EAString___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_ElectricalComponent___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q.equals(syntax))
				emit_ElectricalComponent___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_EnumerationLiteral___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_5__q.equals(syntax))
				emit_EnumerationLiteral___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_5__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Environment___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_9__q.equals(syntax))
				emit_Environment___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_9__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_ErrorModelType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_16__q.equals(syntax))
				emit_ErrorModelType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_16__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_ExtensionPoint___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_5__q.equals(syntax))
				emit_ExtensionPoint___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_5__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_ExternalEvent___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_5__q.equals(syntax))
				emit_ExternalEvent___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_5__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_FeatureModel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q.equals(syntax))
				emit_FeatureModel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_FunctionClientServerInterface___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q.equals(syntax))
				emit_FunctionClientServerInterface___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_FunctionalDevice___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q.equals(syntax))
				emit_FunctionalDevice___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_FunctionalSafetyConcept___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q.equals(syntax))
				emit_FunctionalSafetyConcept___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_GenericConstraintSet___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q.equals(syntax))
				emit_GenericConstraintSet___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Ground___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_9__q.equals(syntax))
				emit_Ground___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_9__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_HardwareComponentType_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q.equals(syntax))
				emit_HardwareComponentType_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_HardwareFunctionType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q.equals(syntax))
				emit_HardwareFunctionType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_HardwarePort___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_9__q.equals(syntax))
				emit_HardwarePort___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_9__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_IOHardwarePin___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q.equals(syntax))
				emit_IOHardwarePin___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_ImplementationLevel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q.equals(syntax))
				emit_ImplementationLevel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_InternalBinding___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_6__q.equals(syntax))
				emit_InternalBinding___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_6__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_LocalDeviceManager___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q.equals(syntax))
				emit_LocalDeviceManager___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_LogicalPath___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q.equals(syntax))
				emit_LogicalPath___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Mission___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_5__q.equals(syntax))
				emit_Mission___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_5__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_ModeEvent___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q.equals(syntax))
				emit_ModeEvent___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Node___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q.equals(syntax))
				emit_Node___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Operation___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q.equals(syntax))
				emit_Operation___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_PortGroup___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q.equals(syntax))
				emit_PortGroup___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_PowerHardwarePin___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q.equals(syntax))
				emit_PowerHardwarePin___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Requirement_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_9__q.equals(syntax))
				emit_Requirement_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_9__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_RequirementsHierarchy_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_9__q.equals(syntax))
				emit_RequirementsHierarchy_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_9__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_RequirementsModel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q.equals(syntax))
				emit_RequirementsModel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Satisfy___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q.equals(syntax))
				emit_Satisfy___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Sensor___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q.equals(syntax))
				emit_Sensor___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Situation___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q.equals(syntax))
				emit_Situation___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_StateEvent___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q.equals(syntax))
				emit_StateEvent___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_SystemModel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_11__q.equals(syntax))
				emit_SystemModel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_11__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_TechnicalSafetyConcept___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q.equals(syntax))
				emit_TechnicalSafetyConcept___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Timing___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_9__q.equals(syntax))
				emit_Timing___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_9__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_TransitionEvent_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q.equals(syntax))
				emit_TransitionEvent_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_UseCase___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_11__q.equals(syntax))
				emit_UseCase___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_11__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_VVActualOutcome___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q.equals(syntax))
				emit_VVActualOutcome___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_VVCase___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q.equals(syntax))
				emit_VVCase___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_VVIntendedOutcome___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q.equals(syntax))
				emit_VVIntendedOutcome___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_VVProcedure___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q.equals(syntax))
				emit_VVProcedure___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_VVStimuli___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q.equals(syntax))
				emit_VVStimuli___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_VVTarget___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q.equals(syntax))
				emit_VVTarget___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Variability___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q.equals(syntax))
				emit_Variability___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_VehicleLevelBinding___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q.equals(syntax))
				emit_VehicleLevelBinding___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_VehicleLevel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q.equals(syntax))
				emit_VehicleLevel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_VerificationValidation___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q.equals(syntax))
				emit_VerificationValidation___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Warrant___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q.equals(syntax))
				emit_Warrant___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_AUTOSAREvent___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_5__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_Actor___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_Actuator___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_Allocation___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_6__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_AnalysisFunctionType_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_AnalysisLevel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_ArchitecturalModel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_6__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_AttributeQuantificationConstraint___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_BasicSoftwareFunctionType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_BehaviorConstraintBindingEvent___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_BehaviorConstraintType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_Behavior___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_CommunicationHardwarePin___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_ComputationConstraint___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_Dependability___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_20__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_DesignFunctionType_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_DesignLevel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_EABoolean___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_EANumerical___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_EAPackage___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_EAString___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_ElectricalComponent___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_EnumerationLiteral___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_5__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_Environment___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_9__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_ErrorModelType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_16__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_ExtensionPoint___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_5__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_ExternalEvent___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_5__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_FeatureModel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_FunctionClientServerInterface___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_FunctionalDevice___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_FunctionalSafetyConcept___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_GenericConstraintSet___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_Ground___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_9__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_HardwareComponentType_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_HardwareFunctionType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_HardwarePort___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_9__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_IOHardwarePin___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_ImplementationLevel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_InternalBinding___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_6__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_LocalDeviceManager___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_LogicalPath___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_Mission___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_5__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_ModeEvent___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_Node___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_Operation___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_PortGroup___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_PowerHardwarePin___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_Requirement_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_9__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_RequirementsHierarchy_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_9__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_RequirementsModel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_Satisfy___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_Sensor___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_Situation___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_StateEvent___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_SystemModel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_11__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_TechnicalSafetyConcept___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_Timing___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_9__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_TransitionEvent_Impl___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_UseCase___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_11__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_VVActualOutcome___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_VVCase___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_12__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_VVIntendedOutcome___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_VVProcedure___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_VVStimuli___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_VVTarget___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_Variability___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_13__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_VehicleLevelBinding___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_VehicleLevel___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_8__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_VerificationValidation___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     shortName=Identifier (ambiguity) (rule end)
	 */
	protected void emit_Warrant___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_10__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
