/*
 * generated by Xtext 2.25.0
 */
package org.omg.qvt10.myqvto.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMyQvtoScopeProvider extends DelegatingScopeProvider {
}
