/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.myspectra;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MySpectraStandaloneSetup extends MySpectraStandaloneSetupGenerated {

	public static void doSetup() {
		new MySpectraStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
