/*
 * generated by Xtext 2.25.0
 */
package org.omg.qvt10.myqvto.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MyQvtoUiModule extends AbstractMyQvtoUiModule {

	public MyQvtoUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
