/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.xcore.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class XcoreUiModule extends AbstractXcoreUiModule {

	public XcoreUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
