/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.myspectra.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.spectra.ui.internal.SpectraActivator;

public class MySpectraUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SpectraActivator.getInstance().getInjector("org.xtext.example.myspectra.MySpectra");
	}

}
