/*
 * generated by Xtext 2.25.0
 */
package org.eclipse.eatxt.simplified.optimized.ide;


/**
 * Use this class to register ide components.
 */
public class EatxtIdeModule extends AbstractEatxtIdeModule {
}
