/*
 * generated by Xtext 2.25.0
 */
package org.omg.qvt10.myqvto.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MyQvtoAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/omg/qvt10/myqvto/parser/antlr/internal/InternalMyQvto.tokens");
	}
}
