/*
 * generated by Xtext 2.25.0
 */
package org.eclipse.eatxt.full.optimized.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class EatxtUiModule extends AbstractEatxtUiModule {

	public EatxtUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
