/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.myxenia.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMyXeniaScopeProvider extends DelegatingScopeProvider {
}
