/*
 * generated by Xtext 2.25.0
 */
package org.prettyprinter.sml.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.prettyprinter.sml.SMLRuntimeModule;
import org.prettyprinter.sml.SMLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SMLIdeSetup extends SMLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SMLRuntimeModule(), new SMLIdeModule()));
	}
	
}
